version: "2.2"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1001
      - PGID=121
      - TZ=Europe/London
    volumes:
      - /home/runner/work/botflow/botflow/config/:/config
      - /home/runner/work/botflow/botflow/downloads/:/downloads
    ports:
      - 9117:9117
